// src/components/transcript.tsx
import { useStore } from '@nanostores/react';
import bSearch from 'binary-search';
import { useEffect, useMemo, useRef } from 'react';
import { $currentTime, $setPlayAt } from '@/stores/player';
import { formatTime } from '@/util/format';

type TranscriptLine = {
  start: number;
  text: string;
};

type Props = {
  transcript: Array<TranscriptLine>;
};

export function Transcript({ transcript }: Props) {
  const currentTime = useStore($currentTime);
  const containerRef = useRef<HTMLDivElement>(null);

  const currentI = useMemo(() => {
    const i = bSearch(
      transcript,
      currentTime,
      (tl, ct) => tl.start / 1000 - ct,
    );

    if (i < 0) {
      return -i - 2;
    }

    return i;
  }, [transcript, currentTime]);

  useEffect(() => {
    if (!containerRef.current) {
      return;
    }

    const line = containerRef.current.querySelector(
      `[data-start="${transcript[currentI]?.start}"]`,
    );

    line?.scrollIntoView({
      behavior: 'smooth',
      block: 'center',
      // @ts-expect-error: not typed in TypeScript
      container: 'nearest',
    });
  }, [currentI, transcript]);

  const handleClick = (start: number) => {
    $setPlayAt.set(start / 1000);
  };

  return (
    <div ref={containerRef} className="size-full overflow-auto p-5">
      <div className="grid grid-cols-[auto_1fr] gap-x-3 gap-y-2">
        {/* <div /> */}
        {/* <h4 className="font-bold text-base text-white leading-[1.4]"> */}
        {/*   Section Heading */}
        {/* </h4> */}

        {transcript.map((line, i) => (
          <button
            key={line.start}
            type="button"
            className="group contents cursor-pointer appearance-none text-left"
            onClick={() => handleClick(line.start)}
          >
            <div
              className={`pt-1 font-mono text-[10px] leading-[1.4] tracking-[-0.2px] ${
                i === currentI
                  ? 'text-indigo-500'
                  : 'text-white/50 group-hover:text-white/70'
              }`}
              data-start={line.start}
            >
              {formatTime(line.start)}
            </div>
            <div className="flex flex-col gap-1.5">
              <p className="text-sm text-white leading-[1.4]">{line.text}</p>
            </div>
          </button>
        ))}
      </div>
    </div>
  );
}

// apps/web-next/src/components/media/transcript.tsx
import { createEffect, createMemo, For } from 'solid-js';
import bSearch from 'binary-search';
import { formatSeconds } from '../../util';
import { currentTime, setSeekTime } from './signals';

export type Props = {
  transcript: Array<{ start: number; text: string }>;
};

export default function Transcript(props: Props) {
  const currentI = createMemo(() => {
    const i = bSearch(
      props.transcript,
      currentTime() * 1000,
      (tl, ct) => tl.start - ct,
    );

    if (i < 0) {
      return -i - 2;
    }

    return i;
  });

  createEffect(() => {
    const el = document.querySelector(
      `[data-start="${props.transcript[currentI()]?.start}"]`,
    ) as HTMLElement;

    if (el) {
      const { parentElement } = el;
      if (parentElement) {
        // scrollIntoView causes the entire viewport to scroll, which can be jarring while entering comments
        // Instead, we scroll the parent element to the top of the element, and we additionally scroll in such a way
        // that the element is offset from the top
        parentElement.scrollTop = Math.max(
          el.offsetTop - parentElement.offsetTop - el.clientHeight,
          0,
        );
      }
    }
  });

  return (
    <dl class="max-h-[500px] space-y-2 overflow-auto scroll-smooth rounded-md bg-gray-100">
      <For each={props.transcript}>
        {(line, i) => (
          <a
            href={`#t=${line.start / 1000}`}
            data-start={line.start}
            onClick={() => setSeekTime(line.start / 1000)}
          >
            <dl
              class="group flex gap-2 px-2 py-1 hover:cursor-pointer"
              classList={{
                'bg-indigo-50': i() === currentI(),
              }}
            >
              <dt class="select-none items-center font-mono text-sm font-medium uppercase text-gray-400 group-hover:text-gray-600">
                {formatSeconds(line.start / 1000)}
              </dt>
              <dd class="text-sm">{line.text}</dd>
            </dl>
          </a>
        )}
      </For>
    </dl>
  );
}
