// apps/web/src/routes/(root)/profile/channels/[id]/edit.tsx
import { RouteDataArgs, useRouteData } from 'solid-start';
import { createServerAction$, createServerData$ } from 'solid-start/server';
import invariant from 'tiny-invariant';
import type {
  ProfileChannelQuery,
  ProfileChannelQueryVariables,
  UpdateChannelMutation,
  UpdateChannelMutationVariables,
} from './__generated__/edit';
import { PageHeading } from '~/components/page-heading';
import { createAuthenticatedClientOrRedirect, gql } from '~/util/gql/server';
import EditableDatalist, {
  DatalistField,
} from '~/components/editable-datalist';

export function routeData({ params, location }: RouteDataArgs<{ id: string }>) {
  return createServerData$(
    async ([, id], { request }) => {
      invariant(id, 'No id provided');
      const client = await createAuthenticatedClientOrRedirect(request);

      const { channelById } = await client.request<
        ProfileChannelQuery,
        ProfileChannelQueryVariables
      >(
        gql`
          query ProfileChannel($id: ShortUuid!) {
            channelById(id: $id) {
              id
              name
            }
          }
        `,
        {
          id,
        },
      );

      return channelById;
    },
    {
      key: () => [
        'channels',
        params['id'],
        location.query['after'],
        location.query['before'],
      ],
      reconcileOptions: {
        key: 'id',
      },
    },
  );
}

const fields: Array<DatalistField> = [
  {
    label: 'Channel Name',
    property: 'name',
    editable: true,
  },
];

export default function EditChannelRoute() {
  const [, submitChannel] = createServerAction$(
    async (form: FormData, { request }) => {
      const channelId = form.get('channelId');
      invariant(typeof channelId === 'string', 'Invalid channelId');
      const name = form.get('name');
      invariant(typeof name === 'string', 'Invalid name');

      const client = await createAuthenticatedClientOrRedirect(request);

      return client.request<
        UpdateChannelMutation,
        UpdateChannelMutationVariables
      >(
        gql`
          mutation UpdateChannel($channelId: ShortUuid!, $name: String!) {
            updateChannel(channelId: $channelId, name: $name) {
              id
            }
          }
        `,
        {
          channelId,
          name,
        },
      );
    },
  );

  const data = useRouteData<typeof routeData>();

  return (
    <>
      <PageHeading title={`Edit Channel: ${data()?.name}`} backButton />
      <submitChannel.Form>
        <input type="hidden" name="channelId" value={data()?.id ?? ''} />
        <EditableDatalist fields={fields} data={data() ?? {}} />
      </submitChannel.Form>
    </>
  );
}

// apps/web/src/routes/(root)/admin/organizations/edit.tsx
import { gql } from 'graphql-request';
import { RouteDataArgs, useRouteData } from 'solid-start';
import {
  createServerAction$,
  createServerData$,
  redirect,
} from 'solid-start/server';
import * as z from 'zod';
import { Show } from 'solid-js';
import {
  AdminOrganizationEditRouteDataQuery,
  AdminOrganizationEditRouteDataQueryVariables,
  AdminUpsertOrganizationMutation,
  AdminUpsertOrganizationMutationVariables,
} from './__generated__/edit';
import { UpsertForm } from '~/components/admin/upsert-form';
import { PageHeading } from '~/components/page-heading';
import { createAdminClientOrRedirect } from '~/util/gql/server';

const UpsertOrganizationSchema = z.object({
  organizationId: z.string().nullable(),
  name: z.string(),
  slug: z.string(),
  description: z.string().nullable(),
});

export function routeData({ location }: RouteDataArgs) {
  return createServerData$(
    async ([id = null], { request }) => {
      const client = await createAdminClientOrRedirect(request);

      const res = await client.request<
        AdminOrganizationEditRouteDataQuery,
        AdminOrganizationEditRouteDataQueryVariables
      >(
        gql`
          query AdminOrganizationEditRouteData(
            $id: ShortUuid = ""
            $prefetch: Boolean!
          ) {
            organizationById(id: $id) @include(if: $prefetch) {
              id
              type
              name
              slug
            }
          }
        `,
        { id, prefetch: Boolean(id) },
      );

      return res;
    },
    { key: () => [location.query['id']] },
  );
}

export default function AdminNewUserRoute() {
  const data = useRouteData<typeof routeData>();

  const [upserting, upsert] = createServerAction$(
    async (form: FormData, event) => {
      const client = await createAdminClientOrRedirect(event.request);

      const variables = UpsertOrganizationSchema.parse(
        Object.fromEntries(
          ['organizationId', 'name', 'slug', 'description'].map((p) => [
            p,
            form.get(p),
          ]),
        ),
      );

      await client.request<
        AdminUpsertOrganizationMutation,
        AdminUpsertOrganizationMutationVariables
      >(
        gql`
          mutation AdminUpsertOrganization(
            $organizationId: ShortUuid
            $name: String!
            $slug: String!
            $description: String
          ) {
            upsertOrganization(
              organizationId: $organizationId
              name: $name
              slug: $slug
              description: $description
            ) {
              id
            }
          }
        `,
        variables,
      );

      return redirect('/admin/organizations');
    },
  );

  return (
    <>
      <PageHeading
        title={`${data()?.organizationById?.id ? 'Edit' : 'New'} Organization`}
        backButton
      />
      <upsert.Form>
        <Show when={data()?.organizationById?.id} keyed>
          {(id) => <input type="hidden" name="organizationId" value={id} />}
        </Show>
        <UpsertForm
          sections={[
            {
              title: 'Meta',
              fields: [
                { type: 'text', name: 'name', label: 'Name' },
                {
                  type: 'select',
                  name: 'type',
                  label: 'Type',
                  options: [
                    { label: 'Church', value: 'CHURCH' },
                    { label: 'Ministry', value: 'MINISTRY' },
                  ],
                },
                { type: 'text', name: 'slug', label: 'Slug' },
              ],
            },
          ]}
          defaultValues={{
            name: data()?.organizationById?.name ?? '',
            type: data()?.organizationById?.type ?? 'MINISTRY',
            slug: data()?.organizationById?.slug ?? '',
          }}
          submitting={upserting.pending}
        />
      </upsert.Form>
    </>
  );
}
