// apps/web/src/routes/auth/login/input.svelte
<script lang="ts">
  export let name: string;
  export let label: string;
  export let type = 'text';
</script>

<div>
  <label for="id" class="block text-sm font-medium text-gray-700">{label}</label
  >
  <input
    id={name}
    {name}
    {type}
    placeholder={label}
    class="block w-full appearance-none rounded-md border border-gray-300 px-3 py-2 placeholder-gray-400 shadow-sm focus:border-indigo-500 focus:outline-none focus:ring-indigo-500 sm:text-sm"
  />
</div>

// apps/web/src/components/form/input.tsx
import type { JSX } from 'solid-js';

export type Props = JSX.IntrinsicElements['input'];

export default function Input(props: Props) {
  return (
    <input
      {...props}
      class="mt-1 block w-full rounded-md border border-gray-300 bg-white py-2 px-3 shadow-sm focus:border-indigo-500 focus:outline-none focus:ring-indigo-500 sm:text-sm"
    />
  );
}
